let GunsArray = [
  {
    name: "AK12",
    rankRequirement: 0,
    damage: "33-20",
    range: "70-130",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "3x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "AN-94",
    rankRequirement: 10,
    damage: "30-23",
    range: "50-120",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "2x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "AS VAL",
    rankRequirement: 15,
    damage: "34-20",
    range: "60-95",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 20
  },
  {
    name: "SCAR-L",
    rankRequirement: 16,
    damage: "33-25",
    range: "60-120",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 30
  },
  {
    name: "M16A4",
    rankRequirement: 22,
    damage: "34-22",
    range: "40-165",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["3x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "G36",
    rankRequirement: 25,
    damage: "31-23",
    range: "80-160",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "2x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "M16A3",
    rankRequirement: 31,
    damage: "32-22",
    range: "80-145",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 30
  },
  {
    name: "TYPE 20",
    rankRequirement: 37,
    damage: "34-24",
    range: "30-140",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 30
  },
  {
    name: "K2",
    rankRequirement: 42,
    damage: "33-20",
    range: "40-140",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "3x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "FAMAS F1",
    rankRequirement: 45,
    damage: "30-20",
    range: "70-140",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi", "Burst"],
    magazineSize: 25
  },
  {
    name: "AK47",
    rankRequirement: 47,
    damage: "41-30",
    range: "70-140",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: [],
    magazineSize: 30
  },
  {
    name: "AUG A3",
    rankRequirement: 52,
    damage: "34-21",
    range: "40-150",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "3x Burst", "Semi"],
    magazineSize: 30
  },
  {
    name: "HK416",
    rankRequirement: 64,
    damage: "31-22",
    range: "80-150",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 30
  },
  {
    name: "AK74",
    rankRequirement: 74,
    damage: "34-23",
    range: "70-150",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi"],
    magazineSize: 30
  },
  {
    name: "AKM",
    rankRequirement: 94,
    damage: "39-28",
    range: "60-120",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "AK 103",
    rankRequirement: 103,
    damage: "37-25",
    range: "60-170",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Semi-Auto"],
    magazineSize: 30
  },
  {
    name: "StG-44",
    rankRequirement: 116,
    damage: "46-29",
    range: "45-160",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "Type 88",
    rankRequirement: 122,
    damage: "34-20",
    range: "75-135",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Burst"],
    magazineSize: 75
  },
  {
    name: "M231",
    rankRequirement: 123,
    damage: "32-20",
    range: "90-150",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Burst", "Auto"],
    magazineSize: 30
  },
  {
    name: "C7A2",
    rankRequirement: 128,
    damage: "29-19",
    range: "80-170",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "M16A1",
    rankRequirement: 28,
    damage: "30-20",
    range: "90-150",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 20
  },
  {
    name: "AUG A1",
    rankRequirement: 20,
    damage: "30-24",
    range: "65-185",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto", "Burst"],
    magazineSize: 30
  },
  {
    name: "AUG A2",
    rankRequirement: 39,
    damage: "35-20",
    range: "50-135",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "L85A2",
    rankRequirement: 55,
    damage: "28-24",
    range: "60-180",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "TAR-21",
    rankRequirement: 111,
    damage: "29-22",
    range: "70-140",
    weaponType: "LMG",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 30
  },
  {
    name: "G11K2",
    rankRequirement: 211,
    damage: "28-21",
    range: "70-145",
    weaponType: "Primary",
    weaponClass: "Assault Rifle",
    firingModes: ["Auto"],
    magazineSize: 45
  },
  {
  name: "MP5K",
  rankRequirement: 0,
  damage: "30-17",
  range: "50-80", // numeric value representing range
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "UMP45",
  rankRequirement: 5,
  damage: "38-21",
  range: "60-100",
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 25,
},
{
  name: "G36C",
  rankRequirement: 7,
  damage: "33-20",
  range: "60-90",
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MP7",
  rankRequirement: 9,
  damage: "30-17",
  range: "40-90",
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "P90",
  rankRequirement: 40,
  damage: 24,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "MP5SD",
  rankRequirement: 5,
  damage: 34,
  range: 50,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "PPSh-41",
  rankRequirement: 25,
  damage: 34,
  range: 30,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 71,
},
{
  name: "Colt SMG 635",
  rankRequirement: 50,
  damage: 30,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "Kriss Vector",
  rankRequirement: 65,
  damage: 33,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 25,
},
{
  name: "MP5/10",
  rankRequirement: 80,
  damage: 38,
  range: 50,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "PP-19 Bizon",
  rankRequirement: 40,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 53,
},
{
  name: "K7",
  rankRequirement: 70,
  damage: 29,
  range: 25,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 40,
},
{
  name: "AUG A3 Para",
  rankRequirement: 90,
  damage: 32,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 25,
},
{
  name: "MP5",
  rankRequirement: 10,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MP10",
  rankRequirement: 30,
  damage: 30,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "Colt LMG",
  rankRequirement: 45,
  damage: 28,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "CBR-C",
  rankRequirement: 60,
  damage: 32,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MP5/4",
  rankRequirement: 75,
  damage: 38,
  range: 50,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "Vector 45",
  rankRequirement: 100,
  damage: 30,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "AUG A1 Para",
  rankRequirement: 20,
  damage: 33,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "FAL Para Shorty",
  rankRequirement: 75,
  damage: 38,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "L2A3",
  rankRequirement: 30,
  damage: 32,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 32,
},
{
  name: "SR-3M",
  rankRequirement: 45,
  damage: 34,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MX4",
  rankRequirement: 55,
  damage: 30,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "Uzi",
  rankRequirement: 65,
  damage: 34,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 32,
},
{
  name: "PP-19",
  rankRequirement: 75,
  damage: 33,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 55,
},
{
  name: "Colt 9mm SMG",
  rankRequirement: 85,
  damage: 28,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 32,
},
  {
  name: "CZ Scorpion Evo 3 A1",
  rankRequirement: 110,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "FN P90 TR",
  rankRequirement: 120,
  damage: 24,
  range: 40,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "Honey Badger",
  rankRequirement: 130,
  damage: 33,
  range: 45,
  weaponType: "Primary",
  weaponClass: "PDW",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "M60",
  rankRequirement: 0,
  damage: 48,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "L86 LSW",
  rankRequirement: 15,
  damage: 34,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "RPK",
  rankRequirement: 20,
  damage: 42,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 45,
},
{
  name: "Scar-HAMR",
  rankRequirement: 35,
  damage: 34,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "MG36",
  rankRequirement: 40,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "Rheinmetall MG3KWS",
  rankRequirement: 5,
  damage: 50,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "Colt LMG",
  rankRequirement: 50,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "M249",
  rankRequirement: 65,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "AWS",
  rankRequirement: 80,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "HK21",
  rankRequirement: 40,
  damage: 40,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "AUG HBAR",
  rankRequirement: 70,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "L115A3",
  rankRequirement: 90,
  damage: 35,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "RPK74",
  rankRequirement: 10,
  damage: 40,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 45,
},
{
  name: "M240",
  rankRequirement: 30,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "L22",
  rankRequirement: 60,
  damage: 28,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MG3",
  rankRequirement: 75,
  damage: 48,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 50,
},
{
  name: "M60",
  rankRequirement: 100,
  damage: 50,
  range: 70,
  weaponType: "Primary",
  weaponClass: "LMG",
  firingModes: ["Automatic"],
  magSize: 100,
},
{
  name: "Intervention",
  rankRequirement: 0,
  damage: 100,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 5,
},
{
  name: "Remington 700",
  rankRequirement: 10,
  damage: 80,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 10,
},
{
  name: "Dragunov SVU",
  rankRequirement: 20,
  damage: 60,
  range: 90,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "AWSM",
  rankRequirement: 30,
  damage: 100,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 7,
},
{
  name: "BFG 50",
  rankRequirement: 40,
  damage: 100,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Single Shot"],
  magSize: 1,
},
{
  name: "Mosin Nagant",
  rankRequirement: 5,
  damage: 95,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 5,
},
{
  name: "Steyr Scout",
  rankRequirement: 50,
  damage: 75,
  range: 90,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 10,
},
{
  name: "Dragunov SVDS",
  rankRequirement: 60,
  damage: 70,
  range: 90,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "VSS Vintorez",
  rankRequirement: 70,
  damage: 60,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "WA2000",
  rankRequirement: 80,
  damage: 80,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 6,
},
{
  name: "M107",
  rankRequirement: 90,
  damage: 95,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Single Shot"],
  magSize: 5,
},
{
  name: "TRG-42",
  rankRequirement: 100,
  damage: 80,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 10,
},
{
  name: "Hecate II",
  rankRequirement: 110,
  damage: 100,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Single Shot"],
  magSize: 7,
},
{
  name: "AWM",
  rankRequirement: 120,
  damage: 95,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Bolt-Action"],
  magSize: 10,
},
{
  name: "BFG 50",
  rankRequirement: 130,
  damage: 100,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Sniper Rifle",
  firingModes: ["Single Shot"],
  magSize: 1,
},
{
  name: "M4A1",
  rankRequirement: 0,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "G36C",
  rankRequirement: 15,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "M4",
  rankRequirement: 20,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "L22",
  rankRequirement: 35,
  damage: 28,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "SCAR PDW",
  rankRequirement: 40,
  damage: 34,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "AKU-12",
  rankRequirement: 5,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "AUG A2",
  rankRequirement: 50,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "M4A4",
  rankRequirement: 65,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "Honey Badger",
  rankRequirement: 80,
  damage: 33,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "K1A",
  rankRequirement: 40,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "SR-3M",
  rankRequirement: 70,
  damage: 34,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "Groza-1",
  rankRequirement: 90,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "FAL 50.63 Para Shorty",
  rankRequirement: 10,
  damage: 38,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "AK105",
  rankRequirement: 30,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MC51SD",
  rankRequirement: 60,
  damage: 38,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "AUG A3",
  rankRequirement: 75,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "KAC SRR",
  rankRequirement: 100,
  damage: 75,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "X95R",
  rankRequirement: 110,
  damage: 32,
  range: 50,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "FAL Para Shorty",
  rankRequirement: 120,
  damage: 38,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "FAMAS F1",
  rankRequirement: 130,
  damage: 29,
  range: 45,
  weaponType: "Primary",
  weaponClass: "Carbine",
  firingModes: ["Automatic"],
  magSize: 30,
},
{
  name: "MK11",
  rankRequirement: 0,
  damage: 40,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "SKS",
  rankRequirement: 10,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "SL-8",
  rankRequirement: 20,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "VSS Vintorez",
  rankRequirement: 30,
  damage: 35,
  range: 70,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "SCAR SSR",
  rankRequirement: 40,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Dragunov SVDS",
  rankRequirement: 5,
  damage: 40,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "Beowulf TCR",
  rankRequirement: 50,
  damage: 48,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "AUG A3 7.62",
  rankRequirement: 65,
  damage: 35,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "SCAR-H",
  rankRequirement: 80,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "MSG90",
  rankRequirement: 40,
  damage: 50,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "SA58 SPR",
  rankRequirement: 70,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Beowulf ECR",
  rankRequirement: 90,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Henry 45-70",
  rankRequirement: 10,
  damage: 65,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Lever-Action"],
  magSize: 5,
},
{
  name: "SCAR-HAMR",
  rankRequirement: 30,
  damage: 32,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Henry 45-70",
  rankRequirement: 60,
  damage: 65,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Lever-Action"],
  magSize: 5,
},
{
  name: "SKS",
  rankRequirement: 75,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "AG-3",
  rankRequirement: 100,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "K14",
  rankRequirement: 110,
  damage: 48,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "SL-8",
  rankRequirement: 120,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "MSG90",
  rankRequirement: 130,
  damage: 50,
  range: 80,
  weaponType: "Primary",
  weaponClass: "DMR",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "FAL 50.00",
  rankRequirement: 0,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "M14",
  rankRequirement: 10,
  damage: 40,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "AG-3",
  rankRequirement: 20,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "SCAR-H",
  rankRequirement: 30,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "Beowulf ECR",
  rankRequirement: 40,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "HK21",
  rankRequirement: 5,
  damage: 40,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "SKS",
  rankRequirement: 50,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "SCAR-HAMR",
  rankRequirement: 65,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "AG-3",
  rankRequirement: 80,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "M60",
  rankRequirement: 40,
  damage: 48,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "AK12BR",
  rankRequirement: 70,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "SCAR SSR",
  rankRequirement: 90,
  damage: 34,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Beowulf TCR",
  rankRequirement: 10,
  damage: 48,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "FAL Para Shorty",
  rankRequirement: 30,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "G3",
  rankRequirement: 60,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "SKS",
  rankRequirement: 75,
  damage: 45,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "MK11",
  rankRequirement: 100,
  damage: 40,
  range: 80,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 20,
},
{
  name: "Scar-HAMR",
  rankRequirement: 110,
  damage: 32,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "SCAR-H",
  rankRequirement: 120,
  damage: 38,
  range: 70,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Automatic"],
  magSize: 20,
},
{
  name: "L115A3",
  rankRequirement: 130,
  damage: 75,
  range: 100,
  weaponType: "Primary",
  weaponClass: "Battle Rifle",
  firingModes: ["Semi-Automatic"],
  magSize: 10,
},
{
  name: "Remington 870",
  rankRequirement: 0,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 5,
},
{
  name: "KSG-12",
  rankRequirement: 10,
  damage: 26,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 14,
},
{
  name: "DBV12",
  rankRequirement: 20,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Automatic"],
  magSize: 10,
},
{
  name: "KS-23M",
  rankRequirement: 30,
  damage: 35,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 3,
},
{
  name: "Stevens DB",
  rankRequirement: 40,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 10,
},
{
  name: "Saiga-12",
  rankRequirement: 5,
  damage: 26,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Automatic"],
  magSize: 10,
},
{
  name: "Spas-12",
  rankRequirement: 50,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Semi-Automatic"],
  magSize: 8,
},
{
  name: "UTS-15",
  rankRequirement: 65,
  damage: 26,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 14,
},
{
  name: "Serbu Shotgun",
  rankRequirement: 80,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 3,
},
{
  name: "Remington 870 MCS",
  rankRequirement: 40,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Pump-Action"],
  magSize: 10,
},
{
  name: "H&R 1871",
  rankRequirement: 70,
  damage: 32,
  range: 40,
  weaponType: "Primary",
  weaponClass: "Shotgun",
  firingModes: ["Break-Action"],
  magSize: 1,
},
];


export {GunsArray}